name: shamba_eye
description: "Crop disease detection and analysis mobile app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # HTTP Requests
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Image Picking (Camera & Gallery)
  image_picker: ^1.1.2
  
  # Network Image Caching
  cached_network_image: ^3.3.0
  
  # Toast Messages
  fluttertoast: ^8.2.4
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Advanced HTTP Client
  dio: ^5.4.0+1
  
  # Image Processing
  image: ^4.1.7
  
  # Loading Shimmer Effect
  shimmer: ^3.0.0
  
  # Pull to Refresh
  pull_to_refresh: ^2.0.0

  intl: ^0.18.1 

  flutter_pytorch_lite: ^0.1.0+3

  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets for images
  assets:
    - assets/models/
    - assets/treatment_advice.json